language: cpp

dist: trusty
addons:
  apt:
    packages:
      - perl
      - re2c
      - autoconf
      - libboost-all-dev
      - procserv
      - libpcre3-dev

script:
  - set -e
  - make update
  - make release
  - cat configure/RELEASE
  - cp -v ci/AREA_DETECTOR_RELEASE.local areaDetector/configure/RELEASE.local
  - make

