language: cpp

dist: trusty
addons:
  apt:
    packages:
      - perl
      - re2c
      - autoconf  # pvaPy
      - libboost-all-dev  # pvaPy
      - procserv  # optional, used by ci-scripts/run-epics-iocs-on-procserv.sh

#cache:
#  directories:
#    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

script:
  - git fetch --unshallow
  - git submodule foreach git fetch --unshalow
  - git submodule update --recursive --remote
  - make update
  - make release

