language: cpp

dist: trusty
addons:
  apt:
    packages:
      - perl
      - re2c
      - autoconf
      - libboost-all-dev
      - procserv

script:
  - make update
  - make release
  - cp -v ci/AREA_DETECTOR_RELEASE.local areaDetector/configure/RELEASE.local
  - make

