trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt-get -y install libreadline-dev
    sudo apt-get -y install perl re2c libboost-all-dev
  displayName: 'Install Packages'

- script: |
    make update
  displayName: 'Update git repos'

- script: |
    make release
  displayName: 'Make Release Files'

- script: |
    configure/modify_release.py ADSIMDETECTOR SET areaDetector/configure/RELEASE.local
    configure/modify_release.py ADFASTCCD     SET areaDetector/configure/RELEASE.local
    configure/modify_release.py ADPROSILICA   SET areaDetector/configure/RELEASE.local
  displayName: 'Modify AD Release File'
  
- script: |
    make 
  displayName: 'Build epics-modules'
