trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt-get -y install libreadline-dev
    sudo apt-get -y install perl re2c libboost-all-dev
  displayName: 'Install Packages'

- script: |
    make update
    make release
    make 
  displayName: 'Run a multi-line script'
